### ISSUE TITLE
status of subrepo gpnetwork

### ISSUE THREAD

**Issue by mckaygerhard** [gfxprim/gpnetwork#1]
i check your  gfxprim  and it looks great.. search for all the subprojects and found this also.. what is the status of this gpnetwork project? how to compile and details?

**Comment by metan-ucw** [comment]
Sorry I've missed this issue somehow. I guess that gfxprim compilation and pre-build packages are explained quite well in the documentation at http://gfxprim.ucw.cz.

For this particular application you need to install libnl-dev netlink library as well.

**Comment by mckaygerhard** [comment]
err i mean. .. 

* the readme does not mentiion your  libnl-dev netlink library 
* the readme does not mention what is the purpose of this app
* the project is not selft explanatory: is a net manager, net command line app, net applet? network of what?
* the readme does not mention if this need dbus communication

men is so obvious the issue! XD i read the code today and noted that this are some kind of network manager 

and finally the web page of gfxprim does not mention so much about this project of gpnetwork, of course we can read the code but you must think on end users also.. XD ;-)  :face_holding_back_tears:

**Comment by metan-ucw** [comment]
Ah so it is about documentation, that can surely improve, I will try do do something about it.
